### ISSUE TITLE
Planning: clear purpose

### ISSUE THREAD

**Issue by codebyMai** [codebyMai/art-shop#4]
As a **first-time user** I want **the website to have a clear purpose** so that **I can immediately know if it is something I am interested in**

**Acceptance criteria:**
- Purpose of the website evident at a glance

**Tasks:**
- [x] choose appropriate hero image
- [x] choose appropriate title
- [x] clearly define purpose (e-commerce)
